// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnn_lA2ZUJhyruVzHnaSDmctHRNRoHpE4',
    appId: '1:188689305252:web:8767c3ecfe48b39fdea031',
    messagingSenderId: '188689305252',
    projectId: 'whatsapp-prectice',
    authDomain: 'whatsapp-prectice.firebaseapp.com',
    storageBucket: 'whatsapp-prectice.appspot.com',
    measurementId: 'G-5ZPYBJ89B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnYzAsPjanw_2YNvoWSbfrA7wxQh7B3H8',
    appId: '1:188689305252:android:1450615c3ae1058edea031',
    messagingSenderId: '188689305252',
    projectId: 'whatsapp-prectice',
    storageBucket: 'whatsapp-prectice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiLpVzT6g55iFlLP_gJe6neEs3OhXgK-o',
    appId: '1:188689305252:ios:34e411129845aa53dea031',
    messagingSenderId: '188689305252',
    projectId: 'whatsapp-prectice',
    storageBucket: 'whatsapp-prectice.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiLpVzT6g55iFlLP_gJe6neEs3OhXgK-o',
    appId: '1:188689305252:ios:6ddf5e832d139defdea031',
    messagingSenderId: '188689305252',
    projectId: 'whatsapp-prectice',
    storageBucket: 'whatsapp-prectice.appspot.com',
    iosBundleId: 'com.example.whatsapp.RunnerTests',
  );
}
